/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PicksGroupIdYearWeekRouteImport } from './routes/picks.$groupId.$year.$week'

const PicksGroupIdYearWeekRoute = PicksGroupIdYearWeekRouteImport.update({
  id: '/picks/$groupId/$year/$week',
  path: '/picks/$groupId/$year/$week',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/picks/$groupId/$year/$week': typeof PicksGroupIdYearWeekRoute
}
export interface FileRoutesByTo {
  '/picks/$groupId/$year/$week': typeof PicksGroupIdYearWeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/picks/$groupId/$year/$week': typeof PicksGroupIdYearWeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/picks/$groupId/$year/$week'
  fileRoutesByTo: FileRoutesByTo
  to: '/picks/$groupId/$year/$week'
  id: '__root__' | '/picks/$groupId/$year/$week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PicksGroupIdYearWeekRoute: typeof PicksGroupIdYearWeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/picks/$groupId/$year/$week': {
      id: '/picks/$groupId/$year/$week'
      path: '/picks/$groupId/$year/$week'
      fullPath: '/picks/$groupId/$year/$week'
      preLoaderRoute: typeof PicksGroupIdYearWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PicksGroupIdYearWeekRoute: PicksGroupIdYearWeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
